### ISSUE TITLE
The `set-output` command is deprecated

### ISSUE THREAD

**Issue by IvekSRC** [cardinalby/git-get-release-action#11]
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by cardinalby** [comment]
@IvekSRC Thanks for reminding! Upgraded in version `1.2.4` (also available under `v1`). Please check!

**Comment by IvekSRC** [comment]
Thank you for this!
