### ISSUE TITLE
Annotation (actions uses Node.js version which is deprecated)

### ISSUE THREAD

**Issue by seiya-git** [cardinalby/git-get-release-action#16]
The following actions uses Node.js version which is deprecated and will be forced to run on node20: cardinalby/git-get-release-action@1.2.4. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Comment by cardinalby** [comment]
Both `@v1` and `@master` have `using: 'node20'`, it should not product the warning. What version do you use?

**Comment by seiya-git** [comment]
v1.2.4, that version uses node 16

**Comment by cardinalby** [comment]
Use `@1.2.5` or `@v1`

**Comment by seiya-git** [comment]
https://github.com/marketplace/actions/git-get-release-action
I see. Marketplace propose 1.2.4 because no 1.2.5 release was created (only tag)
Thanks
