### ISSUE TITLE
feature request: add option to getReleaseByName

### ISSUE THREAD

**Issue by jeacott1** [cardinalby/git-get-release-action#4]
hi, 
 very helpful project, but when dealing with draft releases this action can't find the release info.
it would be great if an option were added to find features by name, as tags don't get created until after a release is converted from draft.

**Comment by cardinalby** [comment]
@jeacott1 Thanks for the feedback!

Check out `cardinalby/git-get-release-action@v1.1` and new `releaseName` input.
Also, you can find a draft release using branch name as a `commitSha` input.

Please test and let me know if it works as expected.
