### ISSUE TITLE
Error: Unable to find version `v1.1`

### ISSUE THREAD

**Issue by daleu** [cardinalby/git-get-release-action#6]
Hi!

Today I was about to run a GitHub action, and suddenly this error occurred: 
![image](https://user-images.githubusercontent.com/19390285/146233051-d1aa2cec-8f9c-4fea-b9ab-2986f57807a3.png)

In my GitHub workflow I have the following fragment of code:
![image](https://user-images.githubusercontent.com/19390285/146233406-9a1071a0-ba0c-48a3-a19b-d2b64eb3db2e.png)

It's weird, because it was working one month ago, and I haven't seen any changes since then. I think it could be related with this issue: https://github.com/cardinalby/git-get-release-action/issues/5

Thanks

**Comment by cardinalby** [comment]
Thanks for reporting and sorry for accidentally removing the tag you use. 
I can advise pinning to SHA when you use 3rd-party actions to prevent cases like that :(
Please check it again.

**Comment by daleu** [comment]
Sorry for the late response! It's working!

Thanks! :)
