### ISSUE TITLE
`body_text` and `body_html` are not available

### ISSUE THREAD

**Issue by dsine-de** [cardinalby/git-get-release-action#7]
Hi!

The readme lists the properties `body_text` and `body_html` as output options, but on the Github API page there is just `body` and the properties are empty when I try to use them.

Also, the `body` output has line breaks in it, is there a way to get it directly like it comes back from the API (as a JSON string with `\n` line breaks) so the value can be used in a new request that has a JSON body?

Thank you!

**Comment by dsine-de** [comment]
Ah, so the `body` output is not a string (which I can use directly in e.g. in a `curl` run) but a JSON and I need to convert it - ok, did not get that.

Thank you, that seems to work!

**Comment by dsine-de** [comment]
Ok - I works like that:

```yaml
...
      - shell: bash
        run: |
          curl -X POST -H 'Content-Type:application/json' -d @- https://myapi-host/api 'EOF'
          {"test":${{toJSON(steps.getLatestRelease.outputs.body)}}}
          EOF
```

**Comment by cardinalby** [comment]
Great! I'm glad you found a solution because the docs for GitHub's `toJSON` and `fromJSON` aren't completely clear.
So, I'm closing the issue
