### ISSUE TITLE
Error finding an existing release with commit SHA

### ISSUE THREAD

**Issue by ghost** [cardinalby/git-get-release-action#9]
Hi there,

Thanks for this action, it's very useful!

We have a workflow that, on push, gets a release that was created earlier in that workflow using this action. A [recent run failed](https://github.com/cdklabs/cdk-monitoring-constructs/runs/5991317669?check_suite_focus=true):

```
Run cardinalby/git-get-release-action@v1
  with:
    searchLimit: 1
    doNotFailIfNotFound: false
  env:
    GITHUB_TOKEN: ***
Retrieving release for current commit e400[2](https://github.com/cdklabs/cdk-monitoring-constructs/runs/5991317669?check_suite_focus=true#step:2:2)1217feb9726bb622a7cc62[4](https://github.com/cdklabs/cdk-monitoring-constructs/runs/5991317669?check_suite_focus=true#step:2:4)88dd[5](https://github.com/cdklabs/cdk-monitoring-constructs/runs/5991317669?check_suite_focus=true#step:2:5)b8f41f8...
Looking for tag with sha == e40021217feb972[6](https://github.com/cdklabs/cdk-monitoring-constructs/runs/5991317669?check_suite_focus=true#step:2:6)bb622a[7](https://github.com/cdklabs/cdk-monitoring-constructs/runs/5991317669?check_suite_focus=true#step:2:7)cc624[8](https://github.com/cdklabs/cdk-monitoring-constructs/runs/5991317669?check_suite_focus=true#step:2:8)8dd5b8f41f8 ...
Error: Error: Tag not found
```

...despite [a release with that sha](https://github.com/cdklabs/cdk-monitoring-constructs/releases/tag/v0.0.42) existing.

Is there some way to further dig into why it may have failed?

**Comment by echeung-amzn** [comment]
Thanks for the insight. I would've expected that to have worked since it was the latest release, but I've also seen GitHub sometimes order releases strangely.

I'll try removing it and hope for the best.

**Comment by cardinalby** [comment]
I also noticed that ordering changed after my tests failed last time :) But it related to the case when you have several releases with the same SHA. The action returns the first found and it can varies depending on the order of GitHub API response

**Comment by echeung-amzn** [comment]
Feel free to close this, I'll comment again if it ever crops up again (which hopefully it doesn't!).
